// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webchat-service.proto

package grpc.demo.java.webchat.proto;

public final class WebChatProto {
  private WebChatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatRoomOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webchat.ChatRoom)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string chatRoomId = 1;</code>
     * @return The chatRoomId.
     */
    java.lang.String getChatRoomId();
    /**
     * <code>string chatRoomId = 1;</code>
     * @return The bytes for chatRoomId.
     */
    com.google.protobuf.ByteString
        getChatRoomIdBytes();
  }
  /**
   * Protobuf type {@code webchat.ChatRoom}
   */
  public static final class ChatRoom extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:webchat.ChatRoom)
      ChatRoomOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatRoom.newBuilder() to construct.
    private ChatRoom(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatRoom() {
      chatRoomId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatRoom();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatRoom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              chatRoomId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_ChatRoom_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_ChatRoom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.class, grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.Builder.class);
    }

    public static final int CHATROOMID_FIELD_NUMBER = 1;
    private volatile java.lang.Object chatRoomId_;
    /**
     * <code>string chatRoomId = 1;</code>
     * @return The chatRoomId.
     */
    @java.lang.Override
    public java.lang.String getChatRoomId() {
      java.lang.Object ref = chatRoomId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatRoomId_ = s;
        return s;
      }
    }
    /**
     * <code>string chatRoomId = 1;</code>
     * @return The bytes for chatRoomId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChatRoomIdBytes() {
      java.lang.Object ref = chatRoomId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatRoomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getChatRoomIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chatRoomId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getChatRoomIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chatRoomId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.demo.java.webchat.proto.WebChatProto.ChatRoom)) {
        return super.equals(obj);
      }
      grpc.demo.java.webchat.proto.WebChatProto.ChatRoom other = (grpc.demo.java.webchat.proto.WebChatProto.ChatRoom) obj;

      if (!getChatRoomId()
          .equals(other.getChatRoomId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHATROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getChatRoomId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.demo.java.webchat.proto.WebChatProto.ChatRoom prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webchat.ChatRoom}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webchat.ChatRoom)
        grpc.demo.java.webchat.proto.WebChatProto.ChatRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_ChatRoom_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_ChatRoom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.class, grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.Builder.class);
      }

      // Construct using grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        chatRoomId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_ChatRoom_descriptor;
      }

      @java.lang.Override
      public grpc.demo.java.webchat.proto.WebChatProto.ChatRoom getDefaultInstanceForType() {
        return grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.demo.java.webchat.proto.WebChatProto.ChatRoom build() {
        grpc.demo.java.webchat.proto.WebChatProto.ChatRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.demo.java.webchat.proto.WebChatProto.ChatRoom buildPartial() {
        grpc.demo.java.webchat.proto.WebChatProto.ChatRoom result = new grpc.demo.java.webchat.proto.WebChatProto.ChatRoom(this);
        result.chatRoomId_ = chatRoomId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.demo.java.webchat.proto.WebChatProto.ChatRoom) {
          return mergeFrom((grpc.demo.java.webchat.proto.WebChatProto.ChatRoom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.demo.java.webchat.proto.WebChatProto.ChatRoom other) {
        if (other == grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.getDefaultInstance()) return this;
        if (!other.getChatRoomId().isEmpty()) {
          chatRoomId_ = other.chatRoomId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.demo.java.webchat.proto.WebChatProto.ChatRoom parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.demo.java.webchat.proto.WebChatProto.ChatRoom) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object chatRoomId_ = "";
      /**
       * <code>string chatRoomId = 1;</code>
       * @return The chatRoomId.
       */
      public java.lang.String getChatRoomId() {
        java.lang.Object ref = chatRoomId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chatRoomId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string chatRoomId = 1;</code>
       * @return The bytes for chatRoomId.
       */
      public com.google.protobuf.ByteString
          getChatRoomIdBytes() {
        java.lang.Object ref = chatRoomId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatRoomId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string chatRoomId = 1;</code>
       * @param value The chatRoomId to set.
       * @return This builder for chaining.
       */
      public Builder setChatRoomId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chatRoomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string chatRoomId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatRoomId() {
        
        chatRoomId_ = getDefaultInstance().getChatRoomId();
        onChanged();
        return this;
      }
      /**
       * <code>string chatRoomId = 1;</code>
       * @param value The bytes for chatRoomId to set.
       * @return This builder for chaining.
       */
      public Builder setChatRoomIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chatRoomId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:webchat.ChatRoom)
    }

    // @@protoc_insertion_point(class_scope:webchat.ChatRoom)
    private static final grpc.demo.java.webchat.proto.WebChatProto.ChatRoom DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.demo.java.webchat.proto.WebChatProto.ChatRoom();
    }

    public static grpc.demo.java.webchat.proto.WebChatProto.ChatRoom getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatRoom>
        PARSER = new com.google.protobuf.AbstractParser<ChatRoom>() {
      @java.lang.Override
      public ChatRoom parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatRoom(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatRoom> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatRoom> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.demo.java.webchat.proto.WebChatProto.ChatRoom getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webchat.ChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *The room the message should be sent to
     * </pre>
     *
     * <code>.webchat.ChatRoom chatRoom = 1;</code>
     * @return Whether the chatRoom field is set.
     */
    boolean hasChatRoom();
    /**
     * <pre>
     *The room the message should be sent to
     * </pre>
     *
     * <code>.webchat.ChatRoom chatRoom = 1;</code>
     * @return The chatRoom.
     */
    grpc.demo.java.webchat.proto.WebChatProto.ChatRoom getChatRoom();
    /**
     * <pre>
     *The room the message should be sent to
     * </pre>
     *
     * <code>.webchat.ChatRoom chatRoom = 1;</code>
     */
    grpc.demo.java.webchat.proto.WebChatProto.ChatRoomOrBuilder getChatRoomOrBuilder();

    /**
     * <pre>
     *The content of the given chat message e.g. "Hello world!"
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     *The content of the given chat message e.g. "Hello world!"
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     *Time the message was generated
     * </pre>
     *
     * <code>int64 timeGeneratedEpochMillis = 3;</code>
     * @return The timeGeneratedEpochMillis.
     */
    long getTimeGeneratedEpochMillis();

    /**
     * <pre>
     *User who sent the message
     * </pre>
     *
     * <code>string nickname = 4;</code>
     * @return The nickname.
     */
    java.lang.String getNickname();
    /**
     * <pre>
     *User who sent the message
     * </pre>
     *
     * <code>string nickname = 4;</code>
     * @return The bytes for nickname.
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <pre>
     *Implementation language name e.g. C#, Java, Swift, Javascript, etc.
     * </pre>
     *
     * <code>string clientLanguage = 5;</code>
     * @return The clientLanguage.
     */
    java.lang.String getClientLanguage();
    /**
     * <pre>
     *Implementation language name e.g. C#, Java, Swift, Javascript, etc.
     * </pre>
     *
     * <code>string clientLanguage = 5;</code>
     * @return The bytes for clientLanguage.
     */
    com.google.protobuf.ByteString
        getClientLanguageBytes();
  }
  /**
   * Protobuf type {@code webchat.ChatMessage}
   */
  public static final class ChatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:webchat.ChatMessage)
      ChatMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMessage() {
      message_ = "";
      nickname_ = "";
      clientLanguage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.Builder subBuilder = null;
              if (chatRoom_ != null) {
                subBuilder = chatRoom_.toBuilder();
              }
              chatRoom_ = input.readMessage(grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chatRoom_);
                chatRoom_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 24: {

              timeGeneratedEpochMillis_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              nickname_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              clientLanguage_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_ChatMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.demo.java.webchat.proto.WebChatProto.ChatMessage.class, grpc.demo.java.webchat.proto.WebChatProto.ChatMessage.Builder.class);
    }

    public static final int CHATROOM_FIELD_NUMBER = 1;
    private grpc.demo.java.webchat.proto.WebChatProto.ChatRoom chatRoom_;
    /**
     * <pre>
     *The room the message should be sent to
     * </pre>
     *
     * <code>.webchat.ChatRoom chatRoom = 1;</code>
     * @return Whether the chatRoom field is set.
     */
    @java.lang.Override
    public boolean hasChatRoom() {
      return chatRoom_ != null;
    }
    /**
     * <pre>
     *The room the message should be sent to
     * </pre>
     *
     * <code>.webchat.ChatRoom chatRoom = 1;</code>
     * @return The chatRoom.
     */
    @java.lang.Override
    public grpc.demo.java.webchat.proto.WebChatProto.ChatRoom getChatRoom() {
      return chatRoom_ == null ? grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.getDefaultInstance() : chatRoom_;
    }
    /**
     * <pre>
     *The room the message should be sent to
     * </pre>
     *
     * <code>.webchat.ChatRoom chatRoom = 1;</code>
     */
    @java.lang.Override
    public grpc.demo.java.webchat.proto.WebChatProto.ChatRoomOrBuilder getChatRoomOrBuilder() {
      return getChatRoom();
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     *The content of the given chat message e.g. "Hello world!"
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *The content of the given chat message e.g. "Hello world!"
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMEGENERATEDEPOCHMILLIS_FIELD_NUMBER = 3;
    private long timeGeneratedEpochMillis_;
    /**
     * <pre>
     *Time the message was generated
     * </pre>
     *
     * <code>int64 timeGeneratedEpochMillis = 3;</code>
     * @return The timeGeneratedEpochMillis.
     */
    @java.lang.Override
    public long getTimeGeneratedEpochMillis() {
      return timeGeneratedEpochMillis_;
    }

    public static final int NICKNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object nickname_;
    /**
     * <pre>
     *User who sent the message
     * </pre>
     *
     * <code>string nickname = 4;</code>
     * @return The nickname.
     */
    @java.lang.Override
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *User who sent the message
     * </pre>
     *
     * <code>string nickname = 4;</code>
     * @return The bytes for nickname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTLANGUAGE_FIELD_NUMBER = 5;
    private volatile java.lang.Object clientLanguage_;
    /**
     * <pre>
     *Implementation language name e.g. C#, Java, Swift, Javascript, etc.
     * </pre>
     *
     * <code>string clientLanguage = 5;</code>
     * @return The clientLanguage.
     */
    @java.lang.Override
    public java.lang.String getClientLanguage() {
      java.lang.Object ref = clientLanguage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientLanguage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *Implementation language name e.g. C#, Java, Swift, Javascript, etc.
     * </pre>
     *
     * <code>string clientLanguage = 5;</code>
     * @return The bytes for clientLanguage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientLanguageBytes() {
      java.lang.Object ref = clientLanguage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientLanguage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (chatRoom_ != null) {
        output.writeMessage(1, getChatRoom());
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (timeGeneratedEpochMillis_ != 0L) {
        output.writeInt64(3, timeGeneratedEpochMillis_);
      }
      if (!getNicknameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nickname_);
      }
      if (!getClientLanguageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, clientLanguage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (chatRoom_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getChatRoom());
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (timeGeneratedEpochMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeGeneratedEpochMillis_);
      }
      if (!getNicknameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, nickname_);
      }
      if (!getClientLanguageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, clientLanguage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.demo.java.webchat.proto.WebChatProto.ChatMessage)) {
        return super.equals(obj);
      }
      grpc.demo.java.webchat.proto.WebChatProto.ChatMessage other = (grpc.demo.java.webchat.proto.WebChatProto.ChatMessage) obj;

      if (hasChatRoom() != other.hasChatRoom()) return false;
      if (hasChatRoom()) {
        if (!getChatRoom()
            .equals(other.getChatRoom())) return false;
      }
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (getTimeGeneratedEpochMillis()
          != other.getTimeGeneratedEpochMillis()) return false;
      if (!getNickname()
          .equals(other.getNickname())) return false;
      if (!getClientLanguage()
          .equals(other.getClientLanguage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasChatRoom()) {
        hash = (37 * hash) + CHATROOM_FIELD_NUMBER;
        hash = (53 * hash) + getChatRoom().hashCode();
      }
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + TIMEGENERATEDEPOCHMILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeGeneratedEpochMillis());
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickname().hashCode();
      hash = (37 * hash) + CLIENTLANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getClientLanguage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.demo.java.webchat.proto.WebChatProto.ChatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webchat.ChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webchat.ChatMessage)
        grpc.demo.java.webchat.proto.WebChatProto.ChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_ChatMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_ChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.demo.java.webchat.proto.WebChatProto.ChatMessage.class, grpc.demo.java.webchat.proto.WebChatProto.ChatMessage.Builder.class);
      }

      // Construct using grpc.demo.java.webchat.proto.WebChatProto.ChatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (chatRoomBuilder_ == null) {
          chatRoom_ = null;
        } else {
          chatRoom_ = null;
          chatRoomBuilder_ = null;
        }
        message_ = "";

        timeGeneratedEpochMillis_ = 0L;

        nickname_ = "";

        clientLanguage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_ChatMessage_descriptor;
      }

      @java.lang.Override
      public grpc.demo.java.webchat.proto.WebChatProto.ChatMessage getDefaultInstanceForType() {
        return grpc.demo.java.webchat.proto.WebChatProto.ChatMessage.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.demo.java.webchat.proto.WebChatProto.ChatMessage build() {
        grpc.demo.java.webchat.proto.WebChatProto.ChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.demo.java.webchat.proto.WebChatProto.ChatMessage buildPartial() {
        grpc.demo.java.webchat.proto.WebChatProto.ChatMessage result = new grpc.demo.java.webchat.proto.WebChatProto.ChatMessage(this);
        if (chatRoomBuilder_ == null) {
          result.chatRoom_ = chatRoom_;
        } else {
          result.chatRoom_ = chatRoomBuilder_.build();
        }
        result.message_ = message_;
        result.timeGeneratedEpochMillis_ = timeGeneratedEpochMillis_;
        result.nickname_ = nickname_;
        result.clientLanguage_ = clientLanguage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.demo.java.webchat.proto.WebChatProto.ChatMessage) {
          return mergeFrom((grpc.demo.java.webchat.proto.WebChatProto.ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.demo.java.webchat.proto.WebChatProto.ChatMessage other) {
        if (other == grpc.demo.java.webchat.proto.WebChatProto.ChatMessage.getDefaultInstance()) return this;
        if (other.hasChatRoom()) {
          mergeChatRoom(other.getChatRoom());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.getTimeGeneratedEpochMillis() != 0L) {
          setTimeGeneratedEpochMillis(other.getTimeGeneratedEpochMillis());
        }
        if (!other.getNickname().isEmpty()) {
          nickname_ = other.nickname_;
          onChanged();
        }
        if (!other.getClientLanguage().isEmpty()) {
          clientLanguage_ = other.clientLanguage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.demo.java.webchat.proto.WebChatProto.ChatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.demo.java.webchat.proto.WebChatProto.ChatMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private grpc.demo.java.webchat.proto.WebChatProto.ChatRoom chatRoom_;
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc.demo.java.webchat.proto.WebChatProto.ChatRoom, grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.Builder, grpc.demo.java.webchat.proto.WebChatProto.ChatRoomOrBuilder> chatRoomBuilder_;
      /**
       * <pre>
       *The room the message should be sent to
       * </pre>
       *
       * <code>.webchat.ChatRoom chatRoom = 1;</code>
       * @return Whether the chatRoom field is set.
       */
      public boolean hasChatRoom() {
        return chatRoomBuilder_ != null || chatRoom_ != null;
      }
      /**
       * <pre>
       *The room the message should be sent to
       * </pre>
       *
       * <code>.webchat.ChatRoom chatRoom = 1;</code>
       * @return The chatRoom.
       */
      public grpc.demo.java.webchat.proto.WebChatProto.ChatRoom getChatRoom() {
        if (chatRoomBuilder_ == null) {
          return chatRoom_ == null ? grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.getDefaultInstance() : chatRoom_;
        } else {
          return chatRoomBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *The room the message should be sent to
       * </pre>
       *
       * <code>.webchat.ChatRoom chatRoom = 1;</code>
       */
      public Builder setChatRoom(grpc.demo.java.webchat.proto.WebChatProto.ChatRoom value) {
        if (chatRoomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chatRoom_ = value;
          onChanged();
        } else {
          chatRoomBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *The room the message should be sent to
       * </pre>
       *
       * <code>.webchat.ChatRoom chatRoom = 1;</code>
       */
      public Builder setChatRoom(
          grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.Builder builderForValue) {
        if (chatRoomBuilder_ == null) {
          chatRoom_ = builderForValue.build();
          onChanged();
        } else {
          chatRoomBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *The room the message should be sent to
       * </pre>
       *
       * <code>.webchat.ChatRoom chatRoom = 1;</code>
       */
      public Builder mergeChatRoom(grpc.demo.java.webchat.proto.WebChatProto.ChatRoom value) {
        if (chatRoomBuilder_ == null) {
          if (chatRoom_ != null) {
            chatRoom_ =
              grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.newBuilder(chatRoom_).mergeFrom(value).buildPartial();
          } else {
            chatRoom_ = value;
          }
          onChanged();
        } else {
          chatRoomBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *The room the message should be sent to
       * </pre>
       *
       * <code>.webchat.ChatRoom chatRoom = 1;</code>
       */
      public Builder clearChatRoom() {
        if (chatRoomBuilder_ == null) {
          chatRoom_ = null;
          onChanged();
        } else {
          chatRoom_ = null;
          chatRoomBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *The room the message should be sent to
       * </pre>
       *
       * <code>.webchat.ChatRoom chatRoom = 1;</code>
       */
      public grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.Builder getChatRoomBuilder() {
        
        onChanged();
        return getChatRoomFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *The room the message should be sent to
       * </pre>
       *
       * <code>.webchat.ChatRoom chatRoom = 1;</code>
       */
      public grpc.demo.java.webchat.proto.WebChatProto.ChatRoomOrBuilder getChatRoomOrBuilder() {
        if (chatRoomBuilder_ != null) {
          return chatRoomBuilder_.getMessageOrBuilder();
        } else {
          return chatRoom_ == null ?
              grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.getDefaultInstance() : chatRoom_;
        }
      }
      /**
       * <pre>
       *The room the message should be sent to
       * </pre>
       *
       * <code>.webchat.ChatRoom chatRoom = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc.demo.java.webchat.proto.WebChatProto.ChatRoom, grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.Builder, grpc.demo.java.webchat.proto.WebChatProto.ChatRoomOrBuilder> 
          getChatRoomFieldBuilder() {
        if (chatRoomBuilder_ == null) {
          chatRoomBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              grpc.demo.java.webchat.proto.WebChatProto.ChatRoom, grpc.demo.java.webchat.proto.WebChatProto.ChatRoom.Builder, grpc.demo.java.webchat.proto.WebChatProto.ChatRoomOrBuilder>(
                  getChatRoom(),
                  getParentForChildren(),
                  isClean());
          chatRoom_ = null;
        }
        return chatRoomBuilder_;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       *The content of the given chat message e.g. "Hello world!"
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *The content of the given chat message e.g. "Hello world!"
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *The content of the given chat message e.g. "Hello world!"
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *The content of the given chat message e.g. "Hello world!"
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *The content of the given chat message e.g. "Hello world!"
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private long timeGeneratedEpochMillis_ ;
      /**
       * <pre>
       *Time the message was generated
       * </pre>
       *
       * <code>int64 timeGeneratedEpochMillis = 3;</code>
       * @return The timeGeneratedEpochMillis.
       */
      @java.lang.Override
      public long getTimeGeneratedEpochMillis() {
        return timeGeneratedEpochMillis_;
      }
      /**
       * <pre>
       *Time the message was generated
       * </pre>
       *
       * <code>int64 timeGeneratedEpochMillis = 3;</code>
       * @param value The timeGeneratedEpochMillis to set.
       * @return This builder for chaining.
       */
      public Builder setTimeGeneratedEpochMillis(long value) {
        
        timeGeneratedEpochMillis_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Time the message was generated
       * </pre>
       *
       * <code>int64 timeGeneratedEpochMillis = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeGeneratedEpochMillis() {
        
        timeGeneratedEpochMillis_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <pre>
       *User who sent the message
       * </pre>
       *
       * <code>string nickname = 4;</code>
       * @return The nickname.
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *User who sent the message
       * </pre>
       *
       * <code>string nickname = 4;</code>
       * @return The bytes for nickname.
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *User who sent the message
       * </pre>
       *
       * <code>string nickname = 4;</code>
       * @param value The nickname to set.
       * @return This builder for chaining.
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *User who sent the message
       * </pre>
       *
       * <code>string nickname = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNickname() {
        
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *User who sent the message
       * </pre>
       *
       * <code>string nickname = 4;</code>
       * @param value The bytes for nickname to set.
       * @return This builder for chaining.
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientLanguage_ = "";
      /**
       * <pre>
       *Implementation language name e.g. C#, Java, Swift, Javascript, etc.
       * </pre>
       *
       * <code>string clientLanguage = 5;</code>
       * @return The clientLanguage.
       */
      public java.lang.String getClientLanguage() {
        java.lang.Object ref = clientLanguage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientLanguage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *Implementation language name e.g. C#, Java, Swift, Javascript, etc.
       * </pre>
       *
       * <code>string clientLanguage = 5;</code>
       * @return The bytes for clientLanguage.
       */
      public com.google.protobuf.ByteString
          getClientLanguageBytes() {
        java.lang.Object ref = clientLanguage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientLanguage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Implementation language name e.g. C#, Java, Swift, Javascript, etc.
       * </pre>
       *
       * <code>string clientLanguage = 5;</code>
       * @param value The clientLanguage to set.
       * @return This builder for chaining.
       */
      public Builder setClientLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientLanguage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Implementation language name e.g. C#, Java, Swift, Javascript, etc.
       * </pre>
       *
       * <code>string clientLanguage = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientLanguage() {
        
        clientLanguage_ = getDefaultInstance().getClientLanguage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Implementation language name e.g. C#, Java, Swift, Javascript, etc.
       * </pre>
       *
       * <code>string clientLanguage = 5;</code>
       * @param value The bytes for clientLanguage to set.
       * @return This builder for chaining.
       */
      public Builder setClientLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientLanguage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:webchat.ChatMessage)
    }

    // @@protoc_insertion_point(class_scope:webchat.ChatMessage)
    private static final grpc.demo.java.webchat.proto.WebChatProto.ChatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.demo.java.webchat.proto.WebChatProto.ChatMessage();
    }

    public static grpc.demo.java.webchat.proto.WebChatProto.ChatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMessage>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
      @java.lang.Override
      public ChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.demo.java.webchat.proto.WebChatProto.ChatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SendReceiptOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webchat.SendReceipt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool sentSuccessfully = 1;</code>
     * @return The sentSuccessfully.
     */
    boolean getSentSuccessfully();
  }
  /**
   * Protobuf type {@code webchat.SendReceipt}
   */
  public static final class SendReceipt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:webchat.SendReceipt)
      SendReceiptOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendReceipt.newBuilder() to construct.
    private SendReceipt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendReceipt() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SendReceipt();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SendReceipt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sentSuccessfully_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_SendReceipt_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_SendReceipt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.demo.java.webchat.proto.WebChatProto.SendReceipt.class, grpc.demo.java.webchat.proto.WebChatProto.SendReceipt.Builder.class);
    }

    public static final int SENTSUCCESSFULLY_FIELD_NUMBER = 1;
    private boolean sentSuccessfully_;
    /**
     * <code>bool sentSuccessfully = 1;</code>
     * @return The sentSuccessfully.
     */
    @java.lang.Override
    public boolean getSentSuccessfully() {
      return sentSuccessfully_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sentSuccessfully_ != false) {
        output.writeBool(1, sentSuccessfully_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sentSuccessfully_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, sentSuccessfully_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.demo.java.webchat.proto.WebChatProto.SendReceipt)) {
        return super.equals(obj);
      }
      grpc.demo.java.webchat.proto.WebChatProto.SendReceipt other = (grpc.demo.java.webchat.proto.WebChatProto.SendReceipt) obj;

      if (getSentSuccessfully()
          != other.getSentSuccessfully()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENTSUCCESSFULLY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSentSuccessfully());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.demo.java.webchat.proto.WebChatProto.SendReceipt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webchat.SendReceipt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webchat.SendReceipt)
        grpc.demo.java.webchat.proto.WebChatProto.SendReceiptOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_SendReceipt_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_SendReceipt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.demo.java.webchat.proto.WebChatProto.SendReceipt.class, grpc.demo.java.webchat.proto.WebChatProto.SendReceipt.Builder.class);
      }

      // Construct using grpc.demo.java.webchat.proto.WebChatProto.SendReceipt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sentSuccessfully_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.demo.java.webchat.proto.WebChatProto.internal_static_webchat_SendReceipt_descriptor;
      }

      @java.lang.Override
      public grpc.demo.java.webchat.proto.WebChatProto.SendReceipt getDefaultInstanceForType() {
        return grpc.demo.java.webchat.proto.WebChatProto.SendReceipt.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.demo.java.webchat.proto.WebChatProto.SendReceipt build() {
        grpc.demo.java.webchat.proto.WebChatProto.SendReceipt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.demo.java.webchat.proto.WebChatProto.SendReceipt buildPartial() {
        grpc.demo.java.webchat.proto.WebChatProto.SendReceipt result = new grpc.demo.java.webchat.proto.WebChatProto.SendReceipt(this);
        result.sentSuccessfully_ = sentSuccessfully_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.demo.java.webchat.proto.WebChatProto.SendReceipt) {
          return mergeFrom((grpc.demo.java.webchat.proto.WebChatProto.SendReceipt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.demo.java.webchat.proto.WebChatProto.SendReceipt other) {
        if (other == grpc.demo.java.webchat.proto.WebChatProto.SendReceipt.getDefaultInstance()) return this;
        if (other.getSentSuccessfully() != false) {
          setSentSuccessfully(other.getSentSuccessfully());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.demo.java.webchat.proto.WebChatProto.SendReceipt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.demo.java.webchat.proto.WebChatProto.SendReceipt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean sentSuccessfully_ ;
      /**
       * <code>bool sentSuccessfully = 1;</code>
       * @return The sentSuccessfully.
       */
      @java.lang.Override
      public boolean getSentSuccessfully() {
        return sentSuccessfully_;
      }
      /**
       * <code>bool sentSuccessfully = 1;</code>
       * @param value The sentSuccessfully to set.
       * @return This builder for chaining.
       */
      public Builder setSentSuccessfully(boolean value) {
        
        sentSuccessfully_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool sentSuccessfully = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSentSuccessfully() {
        
        sentSuccessfully_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:webchat.SendReceipt)
    }

    // @@protoc_insertion_point(class_scope:webchat.SendReceipt)
    private static final grpc.demo.java.webchat.proto.WebChatProto.SendReceipt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.demo.java.webchat.proto.WebChatProto.SendReceipt();
    }

    public static grpc.demo.java.webchat.proto.WebChatProto.SendReceipt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendReceipt>
        PARSER = new com.google.protobuf.AbstractParser<SendReceipt>() {
      @java.lang.Override
      public SendReceipt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendReceipt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendReceipt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendReceipt> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.demo.java.webchat.proto.WebChatProto.SendReceipt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webchat_ChatRoom_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webchat_ChatRoom_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webchat_ChatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webchat_ChatMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webchat_SendReceipt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webchat_SendReceipt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025webchat-service.proto\022\007webchat\"\036\n\010Chat" +
      "Room\022\022\n\nchatRoomId\030\001 \001(\t\"\217\001\n\013ChatMessage" +
      "\022#\n\010chatRoom\030\001 \001(\0132\021.webchat.ChatRoom\022\017\n" +
      "\007message\030\002 \001(\t\022 \n\030timeGeneratedEpochMill" +
      "is\030\003 \001(\003\022\020\n\010nickname\030\004 \001(\t\022\026\n\016clientLang" +
      "uage\030\005 \001(\t\"\'\n\013SendReceipt\022\030\n\020sentSuccess" +
      "fully\030\001 \001(\0102\203\001\n\007WebChat\022;\n\014JoinChatRoom\022" +
      "\021.webchat.ChatRoom\032\024.webchat.ChatMessage" +
      "\"\0000\001\022;\n\013SendMessage\022\024.webchat.ChatMessag" +
      "e\032\024.webchat.SendReceipt\"\000B,\n\034grpc.demo.j" +
      "ava.webchat.protoB\014WebChatProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_webchat_ChatRoom_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webchat_ChatRoom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webchat_ChatRoom_descriptor,
        new java.lang.String[] { "ChatRoomId", });
    internal_static_webchat_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_webchat_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webchat_ChatMessage_descriptor,
        new java.lang.String[] { "ChatRoom", "Message", "TimeGeneratedEpochMillis", "Nickname", "ClientLanguage", });
    internal_static_webchat_SendReceipt_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_webchat_SendReceipt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webchat_SendReceipt_descriptor,
        new java.lang.String[] { "SentSuccessfully", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
